name: front-dev-deploy

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Setting .env
        run: |
          echo "REACT_APP_API_URI=${{ secrets.REACT_APP_API_URI }}" > .env
          echo "REACT_APP_KAKAO_KEY=${{ secrets.REACT_APP_KAKAO_KEY }}" >> .env

      - name: Replace Kakao Key in index.html
        run: sed -i 's/__REACT_APP_KAKAO_KEY__/${{ secrets.REACT_APP_KAKAO_KEY }}/g' ./build/index.html

      - name: S3 Deploy
        run: aws s3 sync ./build s3://hdaejang.com/ --acl bucket-owner-full-control
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_BUCKET_REGION }}
